name: Build CustomBiomeColors

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # Adoptium OpenJDK

    # Cache Gradle dependencies to speed up builds
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Make gradlew executable (needed on Ubuntu)
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Clean the project
    - name: Clean project
      run: ./gradlew clean

    # Build the project with Gradle
    - name: Build with Gradle
      run: ./gradlew assemble --stacktrace

    # Upload the built JAR as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomBiomeColors-JAR
        path: core/build/libs/CustomBiomeColors-1.3.0-MC-1.21.4.jar
        retention-days: 7
